const projects = [
  {
    nome: "CASA 1",
    descricao: "Descrição da CASA UM",
    categoria: "CASAS",
    detalhes: "lorem ipsum",
    cliente: "Cliente teste",
    imagensModal: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-6.png",
      "../assets/projeto-img-6.png",
    ],
    imagens: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-2.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-5.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
    ],
  },
  {
    nome: "CASA DOIS",
    descricao: "Descrição da CASA 1",
    categoria: "CASAS",
    detalhes: "lorem ipsum",
    cliente: "Cliente teste",
    imagensModal: [
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-6.png",
      "../assets/projeto-img-6.png",
    ],
    imagens: [
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-5.png",
    ],
  },
  {
    nome: "CASA 3",
    descricao: "Descrição da CASA 1",
    categoria: "CASAS",
    detalhes: "lorem ipsum",
    cliente: "Cliente teste",
    imagensModal: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-6.png",
      "../assets/projeto-img-6.png",
    ],
    imagens: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-5.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
    ],
  },
  {
    nome: "Projeto 4",
    descricao: "Descrição da Projeto 1",
    categoria: "INTERIORES",
    detalhes: "lorem ipsum",
    cliente: "Cliente teste",
    imagensModal: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-6.png",
      "../assets/projeto-img-6.png",
    ],
    imagens: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-5.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
    ],
  },
  {
    nome: "Projeto 5",
    descricao: "Descrição da Projeto 1",
    categoria: "INTERIORES",
    detalhes: "lorem ipsum",
    cliente: "Cliente teste",
    imagensModal: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-6.png",
      "../assets/projeto-img-6.png",
    ],
    imagens: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-5.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
    ],
  },
  {
    nome: "Projeto 6",
    descricao: "Descrição da Projeto 1",
    categoria: "INTERIORES",
    detalhes: "lorem ipsum",
    cliente: "Cliente teste",
    imagensModal: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-6.png",
      "../assets/projeto-img-6.png",
    ],
    imagens: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-5.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
    ],
  },
  {
    nome: "Projeto 7",
    descricao: "Descrição da Projeto 2",
    categoria: "COMERCIAL",
    detalhes: "lorem ipsum",
    cliente: "Cliente teste",
    imagensModal: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-6.png",
      "../assets/projeto-img-6.png",
    ],
    imagens: [
      "../assets/projeto-img-1.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-5.png",
      "../assets/projeto-img-4.png",
      "../assets/projeto-img-3.png",
      "../assets/projeto-img-4.png",
    ],
  },
];
