const projects = [
    {
      nome: "CASA 1",
      descricao: "Descrição do CASA 1",
      categoria: "CASAS",
      imagens: [
        "../assets/projeto-img-1.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
        "../assets/projeto-img-5.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
      ],
    },
    {
      nome: "CASA 2",
      descricao: "Descrição do CASA 1",
      categoria: "CASAS",
      imagens: [
        "../assets/projeto-img-4.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-1.png",
        "../assets/projeto-img-4.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-5.png",
      ],
    },
    {
      nome: "CASA 3",
      descricao: "Descrição do CASA 1",
      categoria: "CASAS",
      imagens: [
        "../assets/projeto-img-1.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
        "../assets/projeto-img-5.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
      ],
    },
    {
      nome: "Projeto 4",
      descricao: "Descrição do Projeto 1",
      categoria: "INTERIORES",
      imagens: [
        "../assets/projeto-img-1.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
        "../assets/projeto-img-5.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
      ],
    },
    {
      nome: "Projeto 5",
      descricao: "Descrição do Projeto 1",
      categoria: "INTERIORES",
      imagens: [
        "../assets/projeto-img-1.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
        "../assets/projeto-img-5.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
      ],
    },
    {
      nome: "Projeto 6",
      descricao: "Descrição do Projeto 1",
      categoria: "INTERIORES",
      imagens: [
        "../assets/projeto-img-1.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
        "../assets/projeto-img-5.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
      ],
    },
    {
      nome: "Projeto 7",
      descricao: "Descrição do Projeto 2",
      categoria: "COMERCIAL",
      imagens: [
        "../assets/projeto-img-1.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
        "../assets/projeto-img-5.png",
        "../assets/projeto-img-2.png",
        "../assets/projeto-img-3.png",
        "../assets/projeto-img-4.png",
      ],
    },
  ];